# Generated by Django 5.1.3 on 2024-11-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
