# Generated by Django 5.1.3 on 2024-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_produto_preco_compra_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Tirinha',
        ),
        migrations.RenameField(
            model_name='imagem',
            old_name='produto',
            new_name='tirinha',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='imagem_tirinha'),
        ),
    ]
