# Generated by Django 5.1.3 on 2024-12-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='tirinha',
            old_name='nome',
            new_name='titulo',
        ),
    ]
