# Generated by Django 5.1.3 on 2024-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_rename_titulo_personagem_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='imagem',
            field=models.ImageField(default='media/imagex.jpg', upload_to='imagem_personagem'),
        ),
    ]
