# Generated by Django 5.1.3 on 2024-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_personagem_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
