# Generated by Django 5.1.3 on 2024-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('A', 'Artista'), ('D', 'Administrador')], max_length=1),
        ),
    ]
