# Generated by Django 5.1.3 on 2024-12-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_users_profile_picture_alter_users_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='users',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/'),
        ),
    ]
