# Generated by Django 5.1.3 on 2024-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_users_profile_picture_users_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('A', 'Artista'), ('U', 'Usuario'), ('D', 'Administrador')], max_length=1),
        ),
    ]
